### ISSUE TITLE
Overly-aggressive filtering-out of PulseAudio sources and sinks

### ISSUE THREAD

**Issue by patrakov** [kinetiknz/cubeb#149] opened 2016-09-04 07:16 UTC
Cubeb has some logic in src/cubeb_pulse.c, functions pulse_get_state_from_sink_port() and pulse_get_state_from_source_port() that tries to filter out unplugged devices from enumeration. Unfortunately, it is too aggressive. Namely, it returns CUBEB_DEVICE_STATE_DISABLED for sinks and sources with no ports at all.

By accident, both ALSA and Bluetooth sinks created by module-alsa-card and module-bluez5-device contain ports, so common setups work. However, less common setups involve sources and sinks without ports:
- Manually-loaded module-alsa-source and module-alsa-sink (without module-alsa-card - this is useful e.g. to get SPDIF output in addition to the regular analog output)
- Module-tunnel-source, module-tunnel-sink
- Module-ladspa-sink
- Module-null-sink's monitor is useful for capturing the output of some other application without letting it play to real speakers

One of the important setups broken by upgrading Firefox to a version that contains cubeb with this filter is the headless xrdp setup where the only sinks and sources available are provided by xrdp for forwarding the client's speakers and microphone to the session.

**Comment by kinetiknz** [comment] 2016-09-04 23:38
Thanks for reporting this.  As a temporary workaround, you can revert to the older audio enumeration and capture code by setting media.navigator.audio.full_duplex to false in about:config.

It looks like the old code didn't do much filtering beyond excluding sink monitors.  @achronop do you mind investigating?

**Comment by achronop** [comment] 2016-09-05 06:24
Sure I can take it. Please assign it to me and let me know what is the priority.

**Comment by patrakov** [comment] 2016-09-05 12:02
@kinetiknz thanks for the workaround, it helps

**Comment by kinetiknz** [comment] 2016-09-07 00:02
> Sure I can take it. Please assign it to me and let me know what is the priority.

I can't assign it until you're a collaborator; I've sent you an invite.  Once you accept, you can assign yourself.

Priority will come from the WebRTC team, it doesn't affect media playback so I can't make that call.  Given it's a regression, probably reasonably high priority.  The fix is pretty simple (removing the filtering of devices with no ports), it's just that someone needs to verify the behaviour and ensure the UI looks okay with the unfiltered device list, etc.

**Comment by kinetiknz** [comment] 2017-02-06 23:49
This should be fixed by #224.

**Closed by kinetiknz** 2017-02-06 23:49 UTC
