### ISSUE TITLE
cubeb.h doesn't build with c++latest in VS19 16.6

### ISSUE THREAD

**Issue by Filoppi** [kinetiknz/cubeb#595] opened 2020-06-29 21:16 UTC
`CUBEB_LAYOUT_MONO_LFE = CUBEB_LAYOUT_MONO | CHANNEL_LOW_FREQUENCY,`
That can't be done anymore, error is:
operator '|': deprecated between enumerations of different types

**Comment by ligfx** [comment] 2020-07-22 16:40
Dupe of #533

**Closed** 2020-07-22 18:44 UTC
